# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2018.12.10
# Revision...: --
# Purpose....: Simple compose file to create a 18.4 database
# Notes......: --
#
# Reference..: https://github.com/oehrlis/oudbase
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------
version: '3'
services:
  tspitr:
    image: ${DOCKER_USER}/${DOCKER_REPO}:19.5.0.0
    container_name: tspitr
    hostname: tspitr
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ${DOCKER_VOLUME_BASE}/rman/tspitr:/u01
      - ./db:/u01/config
    ports:
      - 1521
    environment:
      CONTAINER: 'TRUE'
      ORACLE_SID: TRMAN01
      INSTANCE_INIT: /u01/config
      CUSTOM_RSP: /u01/config/etc
      ORADBA_DBC_FILE: dbca19.0.0_custom.dbc.tmpl
      ORADBA_RSP_FILE: dbca19.0.0_custom.rsp.tmpl
# - EOF -----------------------------------------------------------------