# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2019.03.16
# Revision...: --
# Purpose....: Simple compose file to create a 11.2 database conatainer
# Notes......: --
#
# Reference..: https://github.com/oehrlis/oudbase
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------
version: '3'
services:

# single tenant database
  tdb112s:
    image: ${DOCKER_USER}/${DOCKER_REPO}:11.2.0.4
    container_name: tdb112s
    hostname: tdb112s
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ${DOCKER_VOLUME_BASE}/tdb112s:/u01
      - ./config:/u01/config
    ports:
      - "1521"
    environment:
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TDB112S
# - EOF -----------------------------------------------------------------