# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2019.03.16
# Revision...: --
# Purpose....: Simple compose file to create an OUDSM container
# Notes......: --
#
# Reference..: https://github.com/oehrlis/oudbase
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------
version: '3'
services:

# single tenant database
  oud12c:
    image: ${DOCKER_USER}/${DOCKER_REPO}:12.2.1.4.0
    container_name: oud12c
    hostname: oud12c
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ${DOCKER_VOLUME_BASE}/oud12c:/u01
      - ./config:/u01/config
    ports:
      - "1389"
      - "1636"
      - "4444"
    environment:
      INSTANCE_INIT: /u01/config
# - EOF -----------------------------------------------------------------