# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2019.03.16
# Revision...: --
# Purpose....: Simple compose file to create a 18.3 database conatainer
# Notes......: --
#
# Reference..: https://github.com/oehrlis/oudbase
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------
version: '3'
services:

# single tenant database
  tdb183s:
    image: ${DOCKER_USER}/${DOCKER_REPO}:18.3.0.0
    container_name: tdb183s
    hostname: tdb183s
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ${DOCKER_VOLUME_BASE}/tdb183s:/u01
      - ./config:/u01/config
    ports:
      - "1521"
    environment:
      CONTAINER: 'FALSE'
      INSTANCE_INIT: /u01/config
      ORACLE_SID: TDB183S

# multitenant tenant database
  # tdb183c:
  #   image: ${DOCKER_USER}/${DOCKER_REPO}:18.3.0.0
  #   container_name: tdb183c
  #   hostname: tdb183c
  #   restart: unless-stopped
  #   network_mode: bridge
  #   volumes:
  #     - ${DOCKER_VOLUME_BASE}/tdb183c:/u01
  #     - ./config:/u01/config
  #   ports:
  #     - "1521"
  #   environment:
  #     CONTAINER: 'TRUE'
  #     INSTANCE_INIT: /u01/config
  #     ORACLE_SID: TDB183C
# - EOF -----------------------------------------------------------------